---
title: "Research"
---

Interests 

- Mixed models
- Longitudinal Data Analysis
- Simulation
- Statistical computing

Publications 

- Ortega-Lenis, D., Arango-Londoño, D., Hernández-Barajas, F. & Moraga, P. (2024). Effects of climate variability on the spatio-temporal distribution of Dengue in Valle del Cauca, Colombia, from 2001 to 2019. PLoS ONE, 19(10). [link](https://doi.org/10.1371/journal.pone.0311607).
- Hernández-Barajas, F.,Usuga-Manco, O., Patino-Rodríguez, C.& Marmolejo-Ramos, F. (2024). Distributional modelling of positively skewed data via the flexible Weibull extension distribution. Australian & New Zealand Journal of Statistics, 66(3), 306-324. [link](https://doi.org/10.1111/anzs.12423).
- Carvalho, F., de Souza, F., Hernandez-Barajas, F., Usuga-Manco, O., Amado, S. (2024). Odds ratio of occurrence of pain, postural changes, and disabilities of violinists. Journal of Bodywork and Movement Therapies, 39, 356-363. [link](https://doi.org/10.1016/j.jbmt.2024.03.012).
- Khatin-Zadeh, O., Banaruee, H, Farsani, D., Hernandez-Barajas, F., Farina, M & Marmolejo-Ramos, F. (2024). Distributed embodiment of the Persian term dæqi:qæn in forward gestures. Journal of Cultural Cognitive Science, 16, 7081. [link](https://doi.org/10.1007/s41809-023-00136-0).
- Rincón-Maya, C., Guevara-Carazas, F., Hernández-Barajas, F., Patino-Rodriguez, C., & Usuga-Manco, O. (2023). Remaining Useful Life Prediction of Lithium-Ion Battery Using ICC-CNN-LSTM Methodology. Energies, 16, 7081. [link](https://doi.org/10.3390/en16207081).
- Usuga Manco, L. M., Hernández-Barajas, F., & Usuga Manco, O. (2023). Modelos Aditivos Generalizados para optimizar el proceso de hidrofobicidad de la caolinita. Ciencia en Desarrollo, 14(2). [link](https://doi.org/10.19053/01217488.v14.n2.2023.14424).
- Rivera-Baena, O. D., Patiño-Rodríguez, C. E., Úsuga-Manco, O. C., & Hernández-Barajas, F. (2023). ADHE: A Tool to Characterize Higher Education Dropout Phenomenon. Revista Facultad De Ingeniería Universidad De Antioquia. [link](https://doi.org/10.17533/udea.redin.20230519).
- Arango-Botero, D., Hernández-Barajas, F. & Valencia-Arias, A. (2023). Misspecification in Generalized Linear Mixed Models and Its Impact on the Statistical Wald Test. Appl. Sci. 2023, 13, 977, pp. 1–16. [link](https://doi.org/10.3390/app13020977).
- Marmolejo-Ramos, F., Ospina, R. & Hernández-Barajas, F. (2022). The place of probability distributions in statistical learning. A commented book review of ‘Distributions for modeling location, scale, and shape using GAMLSS in R’ by Rigby et al. (2021). Australian & New Zealand Journal of Statistics, pp. 1–7. [lik](https://doi.org/10.1111/anzs.12374).
- Hernández Barajas, F., & Ocampo Naranjo, Y. Y. (2022). Modelos GAMLSS como una alternativa para mejorar el proceso de recubrimiento de instrumentos quirúrgicos con cromoduro. Revista EIA, 19(38), 3818 pp. 1–14. [link](https://doi.org/10.24050/reia.v19i38.1536).
- Usuga, O., Patiño Rodríguez, C., Hernández Barajas, F., & Urrea Montoya, A. (2022). Modelo estadístico para el análisis de variables negativas con aplicación a pruebas de contracción en concreto. Revista EIA, 19(38), 3806 pp. 1–19. [link](https://doi.org/10.24050/reia.v19i38.1526).
- Santana Rodríguez, M. O., Ossa Saraz, G. A., López Martínez, J. L., Hernández Barajas, F., & Garcés Blanquiceth, J. L. (2021). Estimación de la heredabilidad del intervalo entre partos en bovinos Romosinuano mediante el modelo lineal mixto generalizado. Ciencia & Tecnología Agropecuaria, 22(2). [link](https://doi.org/10.21930/rcta.vol22_num2_art:1861).
- Hernández, F. y Cano, B. y Caicedo, E. (2021). Modelos GAMLSS para analizar el grado secado de calcio dihidratado. Revista EIA, e-ISSN 2463-0950, 18(35), 1-13. [link](https://doi.org/10.24050/reia.v18i35.1439).
- Hernández, F. y González-Herrera, L. G. (2020). Aplicación de modelos lineales mixtos para estudiar la producción de leche en vacas de la raza Lucerna. Revista de la Facultad de Ciencias, ISSN electrónico 2357-5549. ISSN online 2357-5549, 9(2), 23-42. [link](https://doi.org/10.15446/rev.fac.cienc.v9n2.84681).
- Mazo, D. y Hernández, F. (2020) LOS RESIDUALES RQR: UNA MEDIDA DIAGNÓSTICA EN R PARA LOS MODELOS CUB. Revista de la Facultad de Ciencias, ISSN electrónico 2357-5549. ISSN online 2357-5549, 9(1), 99-111. [link](https://doi.org/10.15446/rev.fac.cienc.v9n1.79512).
- Hernández, F., Usuga, O. y García, S. (2018)	cubm package in R to fit CUB models. Comunicaciones en Estadística, ISSN electrónico 2339-3076. ISSN impreso 2027-3355, 11(2), 219-238. [link](https://doi.org/10.15332/2422474x.3857).
- Diaz, J. C., Hernández, F. y Usuga, O. (2018)	Paquete ZOIP de R para analizar datos proporcionales inflados con ceros y/o unos. Comunicaciones en Estadística, ISSN electrónico 2339-3076. ISSN impreso 2027-3355, 11(1), 37-61. [link](https://doi.org/10.15332/s2027-3355.2018.0001.02).
- Hernández, F. y Giampaoli, V. (2018)	The Impact of Misspecified Random Effect Distribution in a Weibull Regression Mixed Model. Stats, 1(1), 5. [link](https://doi.org/10.3390/stats1010005).
- Arango, D. y Hernández, F. (2017) El impacto de especificar incorrectamente la distribución de los efectos aleatorios en las estimaciones de modelos lineales generalizados mixtos. Comunicaciones en Estadística, ISSN electrónico 2339-3076. ISSN impreso 2027-3355, 10(2), 247-280. [link](https://doi.org/10.15332/2422474x.3267).
- Hernández, F., Naranjo-Dueñas, G. y Monsalve-Lugo, E. (2017) Estimación del rendimiento de orellana mediante modelos Gamlss. Revista de la Facultad de Ciencias, ISSN electrónico 2357-5549. ISSN impreso 0121-747X, 6(1), 245-254. [link](https://doi.org/10.15446/rev.fac.cienc.v6n1.61119).
- Hernández, F., Torres, M., Arteaga, L. y Castro, C. (2015) GAMLSS models applied in the treatment of agro-industrial waste. Comunicaciones en Estadística, ISNN: 2027-3355, 8(2), 245-254. [link](https://doi.org/10.15332/s2027-3355.2015.0002.07).
- Usuga, O. y Hernández, F. (2012). Bayesian Analysis for Errors in Variables with Changepoint Models. Revista Colombiana de Estadística. V.35(1) 15-38. [link](https://revistas.unal.edu.co/index.php/estad/article/view/30152/30399).
- Hernández, F. y Usuga, O. (2011). Análisis Bayesiano para la distribución Lognormal generalizada aplicada a modelos de falla con censura. Revista Colombiana de Estadística. V.34(1) 95-109. [link](https://revistas.unal.edu.co/index.php/estad/article/view/29888).
- Hernández, F. y Correa, J. C. (2009). Comparación entre tres técnicas de clasificación. Revista Colombiana de Estadística. V.32(2) 247-265. [link](http://www.redalyc.org/articulo.oa?id=89912259005).
