---
title: "Research"
---

<hr>

### Interests
- Mixed models
- Longitudinal Data Analysis
- Simulation
- Statistical computing

<hr>

### Publications
- Hernández, F. y González-Herrera, L. G. (2020). "[Aplicación de modelos lineales mixtos para estudiar la producción de leche en vacas de la raza Lucerna](https://revistas.unal.edu.co/index.php/rfc). Revista de la Facultad de Ciencias, ISSN electrónico 2357-5549. ISSN impreso 0121-747X, 9(2), xx-xx.
- Mazo, D. y Hernández, F. (2020) "[LOS RESIDUALES RQR: UNA MEDIDA DIAGNÓSTICA EN R PARA LOS MODELOS CUB](https://revistas.unal.edu.co/index.php/rfc/article/view/79512/73873)". Revista de la Facultad de Ciencias, ISSN electrónico 2357-5549. ISSN impreso 0121-747X, 9(1), 99-111.
- Hernández, F., Usuga, O. y García, S. (2018)	"[cubm package in R to fit CUB models](http://revistas.usantotomas.edu.co/index.php/estadistica/article/view/11/pdf)". Comunicaciones en Estadística, ISSN electrónico 2339-3076. ISSN impreso 2027-3355, 11(2), 219-238.
- Diaz, J. C., Hernández, F. y Usuga, O. (2018)	"[Paquete ZOIP de R para analizar datos proporcionales inflados con ceros y/o unos](http://revistas.usantotomas.edu.co/index.php/estadistica/article/view/3627/4154)". Comunicaciones en Estadística, ISSN electrónico 2339-3076. ISSN impreso 2027-3355, 11(1), 37-61.
- Hernández, F. y Giampaoli, V. (2018)	"[The Impact of Misspecified Random Effect Distribution in a Weibull Regression Mixed Model](http://www.mdpi.com/2571-905X/1/1/5/htm)". Stats, 1(1), 5.
- Arango, D. y Hernández, F. (2017) "[El impacto de especificar incorrectamente la distribución de los efectos aleatorios en las estimaciones de modelos lineales generalizados mixtos](https://revistas.usantotomas.edu.co/index.php/estadistica/article/view/3267/3833)". Comunicaciones en Estadística, ISSN electrónico 2339-3076. ISSN impreso 2027-3355, 10(2), 247-280.
- Hernández, F., Naranjo-Dueñas, G. y Monsalve-Lugo, E. (2017) "[Estimación del rendimiento de orellana mediante modelos Gamlss](https://revistas.unal.edu.co/index.php/rfc/article/view/61119/60343)". Revista de la Facultad de Ciencias, ISSN electrónico 2357-5549. ISSN impreso 0121-747X, 6(1), 245-254.
- Hernández, F., Torres, M., Arteaga, L. y Castro, C. (2015) "[GAMLSS models applied in the treatment of agro-industrial waste](http://revistas.usta.edu.co/index.php/estadistica/article/viewFile/2176/2447)". Comunicaciones en Estadística, ISNN: 2027-3355, 8(2), 245-254.
- Usuga, O. y Hernández, F. (2012). "[Bayesian Analysis for Errors in Variables with Changepoint Models](https://revistas.unal.edu.co/index.php/estad/article/view/30152/30399)". Revista Colombiana de Estadística, ISSN: 0120-1751, Universidad Nacional De Colombia, Bogotá. V.35(1) 15-38.
- Hernández, F. y Usuga, O. (2011). "[Análisis Bayesiano para la distribución Lognormal generalizada aplicada a modelos de falla con censura](http://www.scielo.org.co/pdf/rce/v34n1/v34n1a05.pdf)". Revista Colombiana de Estadística, ISSN: 0120-1751, Universidad Nacional de Colombia, Bogotá. V.34(1) 95-109.
- Hernández, F. y Correa, J. C. (2009). "[Comparación entre tres técnicas de clasificación](http://www.redalyc.org/articulo.oa?id=89912259005)". Revista Colombiana de Estadística, ISSN: 0120-1751, Universidad Nacional de Colombia, Bogotá. V.32(2) 247-265.

