---
title: "TDG"
---

Lineamientos para dirección del (TDG)

<br>

¿Qué es TDG?

El Trabajo de Grado (TDG) es una asignatura que hace parte del Componente Disciplinar o Profesional de tu programa de estudios, en la que consolidas y concretas un proceso de investigación, de creación o de innovación y que es fruto de la aplicación de tus conocimientos y de los métodos adquiridos durante tu proceso de formación universitaria.

Modalidades

- Trabajos investigativos:
    + Monografía 
    + Participación en proyectos de investigación
- Prácticas de extensión:
    + Pasantías
    + Participación en proyectos de extensión
    + Prácticas docentes
    + Emprendimiento empresarial
-   Asignaturas de posgrado

Informes 

Para el TDG en sus modalidades investigativa y extensión deben presentarse dos informes escritos y cortos que serán evaluados por el docente encargado. 

Reuniones

Para hacer un acompañamiento al estudiante en su TDG se deberán programar al menos dos reuniones donde el estudiante le contará al profesor las actividades que está realizando.


La información presentada aquí fue tomada de este [enlace](https://cienciashumanasyeconomicas.medellin.unal.edu.co/comunicado/Masivos/TRABAJO_DE_GRADO_.pdf).