---
title: "Teaching"
---

- 2021-20
    - Modelos jerárquicos (pregrado)
    - Seminario II de maestría (posgrado)
    - Seminario de especialización (posgrado)
- 2021-10
    - Modelos Lineales Generalizados (posgrado)
    - Simulación estadística (pregrado)
- 2020-20
    - Modelos predictivos (posgrado)
    - Seminario II de maestría (posgrado)
    - Análisis de regresión (pregrado)
- 2020-10
    - Modelos Lineales Generalizados (posgrado)
- 2019-20
    - Modelos jerárquicos (pregrado)
    - Seminario II de maestría (posgrado)
    - Técnicas computacionales en estadística (posgrado)
- 2019-10
    - Simulación estadística (pregrado)
    - Análisis de regresión (pregrado)
- 2018-20
    - Introducción al análisis multivariado (pregrado)
    - Seminario II de maestría (posgrado)
    - Técnicas computacionales en estadística (posgrado)
- 2018-10
    - Elementos de probabilidad y estadística (posgrado)
    - Análisis de regresión (pregrado)
- 2017-20
    - Simulación estadística (pregrado)
    - Análisis de regresión (pregrado)
    - Seminario II de maestría (posgrado)
- 2017-10
    - Elementos de probabilidad y estadística (posgrado)
    - Regresión y diseño de experimentos (posgrado)
- 2016-20
    - Análisis de regresión (pregrado)
    - Introducción al análisis multivariado (posgrado)
    - Seminario de especialización (posgrado)
- 2016-01
    - Simulación estadística (pregrado)
    - Elementos de probabilidad y estadística (posgrado)
- 2015-02
    - Modelos jerárquicos (pregrado)
    - Análisis de regresión (pregrado)
- 2015-01
    - Simulación estadística (pregrado)
    - Elementos de probabilidad y estadística (posgrado)

